export const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE'
export const CHANGE_ENTIRE_LIST = 'CHANGE_ENTIRE_LIST'
export const CHANGE_TOTAL_COUNT = 'CHANGE_TOTAL_COUNT'
export const CHANGE_IS_LOADING = 'CHANGE_IS_LOADING'