name: CI
on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        
    # react项目为npm run-script build，vue项目改为npm run build
    - name: Install and Build
      run: |
        npm install
        npm run-script build
     
    # react项目的FOLDER为build，vue项目改为dist   
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        ACCESS_TOKEN: ${{ secrets.BYTE_REACT_AIRBNB }}
        BRANCH: master
        FOLDER: build

    # 示例：使用环境文件替代 set-output
    - name: Create Environment File
      run: |
        echo "DEPLOY_STATUS=success" > .env

    - name: Use Environment File
      run: |
        source .env
        echo "Deployment status: $DEPLOY_STATUS"
